insert into public.teams (name, code, group_name, flag_emoji) values
('Mexico', 'MEX', 'Grupo A', '🇲🇽'),
('Africa do Sul', 'RSA', 'Grupo A', '🇿🇦'),
('Coreia do Sul', 'KOR', 'Grupo A', '🇰🇷'),
('Tchequia', 'CZE', 'Grupo A', '🇨🇿'),
('Canada', 'CAN', 'Grupo B', '🇨🇦'),
('Bosnia', 'BIH', 'Grupo B', '🇧🇦'),
('Catar', 'QAT', 'Grupo B', '🇶🇦'),
('Suica', 'SUI', 'Grupo B', '🇨🇭'),
('Brasil', 'BRA', 'Grupo C', '🇧🇷'),
('Marrocos', 'MAR', 'Grupo C', '🇲🇦'),
('Haiti', 'HAI', 'Grupo C', '🇭🇹'),
('Escocia', 'SCO', 'Grupo C', '🏴'),
('EUA', 'USA', 'Grupo D', '🇺🇸'),
('Paraguai', 'PAR', 'Grupo D', '🇵🇾'),
('Australia', 'AUS', 'Grupo D', '🇦🇺'),
('Turquia', 'TUR', 'Grupo D', '🇹🇷'),
('Alemanha', 'GER', 'Grupo E', '🇩🇪'),
('Curacao', 'CUW', 'Grupo E', '🇨🇼'),
('Costa do Marfim', 'CIV', 'Grupo E', '🇨🇮'),
('Equador', 'ECU', 'Grupo E', '🇪🇨'),
('Holanda', 'NED', 'Grupo F', '🇳🇱'),
('Japao', 'JPN', 'Grupo F', '🇯🇵'),
('Suecia', 'SWE', 'Grupo F', '🇸🇪'),
('Tunisia', 'TUN', 'Grupo F', '🇹🇳'),
('Belgica', 'BEL', 'Grupo G', '🇧🇪'),
('Egito', 'EGY', 'Grupo G', '🇪🇬'),
('Ira', 'IRN', 'Grupo G', '🇮🇷'),
('Nova Zelandia', 'NZL', 'Grupo G', '🇳🇿'),
('Espanha', 'ESP', 'Grupo H', '🇪🇸'),
('Cabo Verde', 'CPV', 'Grupo H', '🇨🇻'),
('Arabia Saudita', 'KSA', 'Grupo H', '🇸🇦'),
('Uruguai', 'URU', 'Grupo H', '🇺🇾'),
('Franca', 'FRA', 'Grupo I', '🇫🇷'),
('Senegal', 'SEN', 'Grupo I', '🇸🇳'),
('Iraque', 'IRQ', 'Grupo I', '🇮🇶'),
('Noruega', 'NOR', 'Grupo I', '🇳🇴'),
('Argentina', 'ARG', 'Grupo J', '🇦🇷'),
('Argelia', 'ALG', 'Grupo J', '🇩🇿'),
('Austria', 'AUT', 'Grupo J', '🇦🇹'),
('Jordania', 'JOR', 'Grupo J', '🇯🇴'),
('Portugal', 'POR', 'Grupo K', '🇵🇹'),
('RD Congo', 'COD', 'Grupo K', '🇨🇩'),
('Uzbequistao', 'UZB', 'Grupo K', '🇺🇿'),
('Colombia', 'COL', 'Grupo K', '🇨🇴'),
('Inglaterra', 'ENG', 'Grupo L', '🏴'),
('Croacia', 'CRO', 'Grupo L', '🇭🇷'),
('Gana', 'GHA', 'Grupo L', '🇬🇭'),
('Panama', 'PAN', 'Grupo L', '🇵🇦')
on conflict (code) do update set
  name = excluded.name,
  group_name = excluded.group_name,
  flag_emoji = excluded.flag_emoji;
